### ISSUE TITLE
Rst error, objectstorage v1, need an empty line after code-block directive

### ISSUE THREAD

**Issue by kbhawkey** [russell/fairy-slipper#12]
2015-08-24 15:31:29,382 [INFO    ] [pecan.commands.serve][MainThread] "GET /doc/objectstorage/v1/ HTTP/1.1" 200 41807
<string>:199: (ERROR/3) Error in "code-block" directive:
maximum 1 argument(s) allowed, 6 supplied.

.. code-block:: json
   "OS-OAUTH1": {
       "access_token_id": "cce0b8be7"
   }

**Comment by kbhawkey** [comment]
I will add a fix for this.

**Comment by kbhawkey** [comment]
Hi. I propose this fix to tools/wadl_to_swagger.py.

 def visit_programlisting(self, attrs):
        if not attrs:
            self.content.append('::\n')
        else:
            self.content.append('.. code-block:: %s\n\n' % attrs['language'])
        self.nesting = 3

```
def depart_programlisting(self):
    self.content.append('\n')
    self.nesting = 0
```

**Comment by russell** [comment]
I don't know how i missed it, but i stumbled across your branch and merged it.  I have also added a couple of test cases for it 2ef2e2f05526361ddcf7ca548bb0cb606c2143c7.  I have included a way to test just the tags that appear in the wadl:doc parts, so all the para tags and other complex formatting.   Which i imagine are going to be the source of most of the remaining bugs.

You can commit directly to master if you like, I have travis-ci setup, i don't know if it will notify you if you break something, but it will be a good test :)

**Comment by kbhawkey** [comment]
Good, I will take a look at the test cases. I worked off a local branch and
thought I pushed to master.
I was wondering why I did not see the changes on my local master branch
after a fetch.
Thanks.
