### ISSUE TITLE
dbaas.wadl table output with extra header names, wadl_to_swagger

### ISSUE THREAD

**Issue by kbhawkey** [russell/fairy-slipper#17]
The database wadl file in api-site, dbaas.wadl contains several tables.  The file database-v1-swagger.json, generated by wadl_to_swagger contains the tables, but with extra header fields, such as "Field 1", "Field 2", "Field 3" in each table.  See prettytable.py add_row() and its usage in depart_tr(), wadl_to_swagger.py.

**Comment by russell** [comment]
I think this can be fixed by disabling headers in tables that don't have them

``` python
In [1]: import prettytable

In [2]: pt = prettytable.PrettyTable()

In [4]: pt.add_row(['test'])

In [6]: print str(pt)
+---------+
| Field 1 |
+---------+
|   test  |
+---------+

In [8]: pt.header
Out[8]: True

In [10]: pt.header = False

In [11]: print str(pt)
+------+
| test |
+------+
```

**Comment by kbhawkey** [comment]
Good idea.  Also, one table in dbaas.wadl is missing column data which accounts for the row extension and extra add_row() in depart_tr().  For consistency, I will add this check to docbkx_to_json.
