### ISSUE TITLE
Incorrect rendering of code blocks

### ISSUE THREAD

**Issue by russell** [russell/fairy-slipper#24]
Some code blocks are being rendered on one line, but they obviously should span a few.

![screenshot from 2015-09-24 17-32-37](https://cloud.githubusercontent.com/assets/2660/10067763/525f3196-62e2-11e5-99a3-16e734ab7013.png)

**Comment by kbhawkey** [comment]
This may intersect with #25.  I will see what I find.

**Comment by kbhawkey** [comment]
I am closing this issue. Plan to submit a change to the name of the docbkx test. 
Issue #25 should address the formatting of programlisting, code, listitem embedded in paragraphs.
