### ISSUE TITLE
Move repository to openstack organization

### ISSUE THREAD

**Issue by annegentle** [russell/fairy-slipper#37]
Just wanted to note here that we discussed at the Summit to move this repo to use the Gerrit workflow. Let us know in this issue if you have any difficulties with that move. I think it makes sense to move so that projects will know about it and use it for the API docs.

**Comment by russell** [comment]
Yeah, I think anything we can do to prevent people duplicating our work is great.  

I'm assuming that we will also need to move all the issues to launchpad?
Will we need to do anything to get the CI system to use our tox config?

**Comment by annegentle** [comment]
I think we can track issues in http://bugs.launchpad.net/openstack-api-site, sound good?

We'll need to do some CI work in the openstack-infra/project-config I believe so that the tox jobs are run in the gate on each submitted patch. I think potential jobs are:
- migrate wadl (since we need to do this for many services, and make sure it works each time, then eventually remove wadl for each service one-at-a-time)
- build the files (with Sphinx?) as an output 
- copy the files to docs-draft.openstack.org for drafts to review with with patches
- copy the files to developer.openstack.org

**Comment by annegentle** [comment]
Assigning myself -- I'll make a patch like https://review.openstack.org/#/c/151766/ -- which imported the Sphinx theme.  I'll create an ACL list with @russell @joannahuang @kbhawkey for starters, @jtopjian let me know if you'd like to be added as well.

**Comment by jtopjian** [comment]
Hi Anne,

Sorry for the late reply. Thanks for the offer. I think I'll just subscribe to Gerrit notifications and help where I can :smile: 

Joe

**Comment by annegentle** [comment]
Okay, sounds good! I've got a WIP patch up here: https://review.openstack.org/#/c/245352/

**Comment by russell** [comment]
@annegentle I'm having a look over the review.  I'll update an updated patch shortly

**Comment by annegentle** [comment]
Updated based on reviews.

**Comment by annegentle** [comment]
This is still ongoing, awaiting the patch passing an IRC test but I think because of the freenode DDoS attacks still ongoing we may need to wait another week or so.
