### ISSUE TITLE
wadl: programlisting, paragraphs

### ISSUE THREAD

**Issue by kbhawkey** [russell/fairy-slipper#46]
The wadl files appear to have introduced a change in the area of para and programlisting elements. 
As a result, the rst rendering is not correct.  The rendering of literal blocks, code examples in lists will need to be revisited as well as how and where to display curl examples (possibly not in the main description for the operation). See objectstorage as an example.

**Comment by annegentle** [comment]
Ah, object storage tends to have a lot of examples embedded, though mostly it was supposed to be cleaned up to where the user guide has all the `curl` examples. Still, this API also is special in that it has a lot of heading listings, which are in <programlisting> tags. Can you point to one example so I can take a look?

**Comment by kbhawkey** [comment]
I will dig into this a bit more and fix the formatting (or wadl paragraphs) if needed.  It is a formatting problem, not necessarily a content problem.  Still, I am not sure that curl commands and http header request/responses samples belong in the main operation description (see delete container or create(put) container).  The http header fields should be listed in the request and response details.

**Comment by kbhawkey** [comment]
This was fixed by updating the wadl file (listitem and para elements).
