### ISSUE TITLE
Some paths are being converted with double slashes

### ISSUE THREAD

**Issue by russell** [russell/fairy-slipper#6]
e.g. /v3//OS-PKI/revoked from the identity v3 api

**Comment by kbhawkey** [comment]
I am taking a look at this issue.

**Comment by kbhawkey** [comment]
I have a fix for several of the .wadl files.

**Comment by kbhawkey** [comment]
A fix for this bug has been submitted,
https://bugs.launchpad.net/openstack-api-site/+bug/1489023

**Comment by russell** [comment]
Good stuff, I honestly assumed that it must have been a bug in fairy-slipper.

**Comment by kbhawkey** [comment]
I thought it best to make the wadl files consistent for the resource path attribute rather than implement different checks in wadl_to_swagger.py.
