### ISSUE TITLE
migrate.sh fails to install venv

### ISSUE THREAD

**Issue by elmiko** [russell/fairy-slipper#7]
i'm trying to follow the workflow described in the README, but the defaults don't seem to be available.

steps to reproduce:
1. clone new fairy-slipper repository
2. run `./migrate.sh -V`

output is as follows:

``` console
$ ./migrate.sh -V
python: can't open file 'tools/install_venv.py': [Errno 2] No such file or directory
./migrate.sh: line 96: tools/with_venv.sh: No such file or directory
./migrate.sh: line 97: tools/with_venv.sh: No such file or directory
./migrate.sh: line 98: tools/with_venv.sh: No such file or directory
```

**Comment by russell** [comment]
Hi!

Thanks for the bug report.  The supporting scripts are bad at the moment.  But I have just put in a little effort to support the standard OpenStack venv code.  So there is now a `run_server.sh` script that will fire up the webserver in the same environment that is used during the migration.

Happy Hacking!

**Comment by elmiko** [comment]
thanks, i'll give it a try =)

**Comment by elmiko** [comment]
just wanted to add that i tried the latest patch and it installed to venv just fine. thanks for the update!
